version: "3.9"

services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Expose React app on port 3000
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose FastAPI app on port 5000
    # environment:
    #   # Pass environment variables if needed
    #   MONGO_URI: "mongodb+srv://<userName>:<password>@basic-free-tier-cluster.vo3k8.mongodb.net/?retryWrites=true&w=majority&appName=Basic-Free-Tier-Cluster"
    #   DATABASE_NAME: "Mist"
    #   COLLECTION_NAME: "messages"
